#!/bin/bash
LINE="0 4 * * 1 $HOME/script.sh"
LOG_FILE="/var/log/update_script.log"
echo "apt-get update >> $LOG_FILE 2>&1 && apt-get upgrade >> $LOG_FILE 2>&1" > $HOME/script.sh
chmod 755 $HOME/script.sh
(crontab -l ; echo "$LINE") | crontab -
