#!/bin/sh
if [ -e $HOME/filehash.md5 ]; then
	if ! md5sum -c $HOME/filehash.md5 > /dev/null 2>&1 ; then
		echo "The file was modified" | mail -s "Attention!" root
		md5sum /etc/crontab > $HOME/filehash.md5
	fi
else
	md5sum /etc/crontab > $HOME/filehash.md5
fi
# In order to run this script every midnight:
# (crontab -l > /dev/null 2>&1; echo "@midnight $HOME/filehash.md5") | crontab -
